export const crops = [
  {
    id: "1",
    image: "maize",
    title: {
      english: "Maize",
      hausa: "Masara",
      yoruba: "Màízì",
      igbo: "Ọka",
      nupe: "Kaba",
    },
    subtitle: "Zea mays",
  },
  {
    id: "2",
    image: "tomato",
    title: {
      english: "Tomato",
      hausa: "Tumatir",
      yoruba: "Tómátò",
      igbo: "Tọmáto",
      nupe: "Tomato",
    },
    subtitle: "Solanum lycopersicum",
  },
  {
    id: "3",
    image: "onion",
    title: {
      english: "Onion",
      hausa: "Albasa",
      yoruba: "Alubọsa",
      igbo: "Yabasị",
      nupe: "Ganye",
    },
    subtitle: "Allium cepa",
  },
  {
    id: "4",
    image: "rice",
    title: {
      english: "Rice",
      hausa: "Shinkafa",
      yoruba: "Iresi",
      igbo: "Osikapa",
      nupe: "Jenkafa",
    },
    subtitle: "Oryza sativa",
  },
  {
    id: "5",
    image: "beans",
    title: {
      english: "Beans",
      hausa: "Wake",
      yoruba: "Ewa",
      igbo: "Agwa",
      nupe: "Ezo",
    },
    subtitle: "Phaseolus vulgaris",
  },
  {
    id: "6",
    image: "soybeans",
    title: {
      english: "Soybeans",
      hausa: "Wakensoya",
      yoruba: "Ewasoya",
      igbo: "Agwasoya",
      nupe: "ezosoya",
    },
    subtitle: "Phaseolus vulgaris",
  },
  {
    id: "7",
    image: "watermelon",
    title: {
      english: "Watermelon",
      hausa: "Kankana",
      yoruba: "Igi-omi",
      igbo: "Mmanụ",
      nupe: "Kankana",
    },
    subtitle: "Citrullus lanatus",
  },
  {
    id: "8",
    image: "pepper",
    title: {
      english: "Pepper",
      hausa: "Barkono",
      yoruba: "Ata",
      igbo: "Ose",
      nupe: "Atta",
    },
    subtitle: "Capsicum annuum",
  },
  {
    id: "9",
    image: "guneacorn",
    title: {
      english: "GuineaCorn",
      hausa: "Dawa",
      yoruba: "Igi-oke",
      igbo: "Oka-nkwo",
      nupe: "Eyi",
    },
    subtitle: "Sorghum bicolor",
  },
  {
    id: "10",
    image: "groundnut",
    title: {
      english: "Groundnut",
      hausa: "Gyada",
      yoruba: "Epa",
      igbo: "Akhụ",
      nupe: "Gujzha",
    },
    subtitle: "Arachis hypogaea",
  },
  {
    id: "11",
    image: "millet",
    title: {
      english: "Millet",
      hausa: "Gero",
      yoruba: "Àkàn",
      igbo: "Mịlịtị",
      nupe: "Eburo",
    },
    subtitle: "Pennisetum glaucum",
  },
  {
    id: "12",
    image: "cassava",
    title: {
      english: "Cassava",
      hausa: "Rogo",
      yoruba: "Gari",
      igbo: "Akpu",
      nupe: "Manioca",
    },
    subtitle: "Manihot esculenta",
  },
];
